# Generated by Django 5.2.15 on 2026-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_alter_prescriptionitem_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='interaction_status',
            field=models.CharField(choices=[('Skipped', 'Skipped'), ('Completed', 'Completed'), ('Error', 'Error')], default='Skipped', max_length=20),
        ),
    ]
